[theme]
primaryColor="#FF3B3F"
base="dark"
backgroundColor="#F5F5F5"
secondaryBackgroundColor="#85A7FF"
font="roboto"
textColor="#000000"

echo "\
[general]\n\
email = \"your-email@domain.com\"\n\
" > ~/.streamlit/credentials.toml

echo "\
[server]\n\
headless = true\n\
enableCORS=false\n\
port = $PORT\n\
" > ~/.streamlit/config.toml